// <auto-generated />
using ImageFetcherAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImageFetcherAPI.Migrations
{
    [DbContext(typeof(ImageFetcherDbContext))]
    [Migration("20250615114402_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TCSA")
                .HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ImageFetcherAPI.Models.Cat", b =>
                {
                    b.Property<string>("RowId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Breeds")
                        .HasColumnType("TEXT");

                    b.Property<string>("Height")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Width")
                        .HasColumnType("TEXT");

                    b.HasKey("RowId");

                    b.ToTable("Cats", "TCSA");
                });
#pragma warning restore 612, 618
        }
    }
}
